spring:
  application:
    name: instancio-petclinic-jpa-example
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  config:
    import: classpath:/entity-config.yaml
  sql:
    init:
      schema-locations: ""
      data-locations: ""

  jpa:
    generate-ddl: true
    database: default
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        generate-ddl: true
        ddl-auto: update


